name: Python tests with MATLAB engine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    # Set up MATLAB before Python
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024b  # Specify the MATLAB release you want to use
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements-test.txt
        pip install -e .

    - name: Run Python tests with pytest
      run: pytest -s -vv

